### ISSUE TITLE
Name of hotel or public house doesn't need to have quotes

### ISSUE THREAD

**Issue by drgrigg** [dajare/anthony-trollope_can-you-forgive-her#1]
Our house style is not to quote such names.

Eg: `their rotgut stuff at the ‘Cadogan Arms,’` shouldn't have the single quotes. (Chapter 12)
`They is at the ‘Handsome Man’ in the Brompton Road`
`They’re a bidding for the ‘Handsome Man’ already;`

**Comment by dajare** [comment]
Used regex to catch all of these (I hope!!).
