### ISSUE TITLE
Typogrify makes changes which should be accepted

### ISSUE THREAD

**Issue by drgrigg** [dajare/anthony-trollope_can-you-forgive-her#3]
These seem to be mostly putting in hairspaces next to dashes, non-breaking spaces after a Mr. or Mrs., etc. 

So far as I can see the changes are all correct and should be accepted.

**Comment by dajare** [comment]
Done, and committed. **N.b.**:

- `colophon.xhtml` - added a `&nbsp;` in the title of the painting ("Mrs. George Swinton..."); does the colophon get this treatment, too?
- `chapter-35.xhtml` - removed a comma before em-dash (with removal of quotation marks from site-names, `Handsome Man⁠—and as,`) in line 52. 

I have **not** used `[Editorial]` with this commit, as the "typogrify" stage in the Step-by-Step does not use that convention. IF I was mistaken, this can commit can be unpicked for the comma's sake. :/

**Comment by drgrigg** [comment]
No, I think all of that is fine.
